name: Update major version tag on release

on:
  release:
    types: [published]

jobs:
  update-major-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to push tags

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract major version from release tag
        id: get-version
        run: |
          tag="${GITHUB_REF##*/}"
          major_tag=$(echo "$tag" | grep -oP '^v\d+')
          echo "major_tag=$major_tag" >> "$GITHUB_OUTPUT"

      - name: Update major version tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -f ${{ steps.get-version.outputs.major_tag }}
          git push origin ${{ steps.get-version.outputs.major_tag }} --force
